# ESP32-P4-JC1060P470
substitutions:
  name: "ha_touch"
  friendly_name: "HomeAssistant touchscreen"
  room: "Living room"

# Wifi Setup
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Packages
packages:
  - !include addon/backlight.yaml