# ESP32-P4-JC1060P470
substitutions:
  name: "ha-touch"
  friendly_name: "HomeAssistant touchscreen"
  room: "Living room"

# Wifi Setup
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Packages
packages:
  setup:
    url: https://github.com/timbonus/esphome-lvgl/
    file: guition-esp32-p4-jc1060p470/package.yaml
    refresh: 1d